// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmWfwHThDUmFMrvh8-TDgGCVN_b4PkGI0',
    appId: '1:826100488166:web:207628f445ab6aea63e827',
    messagingSenderId: '826100488166',
    projectId: 'e-training-app',
    authDomain: 'e-training-app.firebaseapp.com',
    storageBucket: 'e-training-app.firebasestorage.app',
    measurementId: 'G-6J1PTG833X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1xNsMEkeF-Yyuwmnr6pCN3bKw7UmRPa0',
    appId: '1:826100488166:android:36b78e13d8ac769163e827',
    messagingSenderId: '826100488166',
    projectId: 'e-training-app',
    storageBucket: 'e-training-app.firebasestorage.app',
  );
}
